### ISSUE TITLE
运行不起来啊...

### ISSUE THREAD

**Issue by luguohuakai** [shanghai-edu/radius-1xtest#1]
(env) [root@iZm5edp55jwpn9ovl6hp6aZ radius-1xtest]# ./env/bin/python run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from app import app
  File "/srun3/www/eduroam/radius-1xtest/app/__init__.py", line 9, in <module>
    from app import views
  File "/srun3/www/eduroam/radius-1xtest/app/views.py", line 28
    data = request.get_json()
                            ^
TabError: inconsistent use of tabs and spaces in indentation
(env) [root@iZm5edp55jwpn9ovl6hp6aZ radius-1xtest]#

**Comment by luguohuakai** [comment]
(env) [root@iZm5edp55jwpn9ovl6hp6aZ radius-1xtest]# ./control start
radius-1xtest started..., pid=13906
(env) [root@iZm5edp55jwpn9ovl6hp6aZ radius-1xtest]# ./control status
radius-1xtest is stoped
(env) [root@iZm5edp55jwpn9ovl6hp6aZ radius-1xtest]# ./control stop
./control: line 44: kill: (13906) - No such process
radius-1xtest quit...
(env) [root@iZm5edp55jwpn9ovl6hp6aZ radius-1xtest]#

**Comment by freedomkk-qfeng** [comment]
用 Python 2.7 ~
